set -g mouse on
set -g history-limit 50000

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Wayland clipboard (was xclip on old machine)
set -g @override_copy_command 'wl-copy'
bind -T copy-mode-vi y send -X copy-pipe-and-cancel 'wl-copy'
bind -T copy-mode MouseDragEnd1Pane send -X copy-pipe-and-cancel 'wl-copy'

run '~/.tmux/plugins/tpm/tpm'
